# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # https://github.com/fgrehm/vagrant-cachier#quick-start
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end
 
  config.vm.box = "centos/7"
  config.vm.hostname = "avop"
  config.vm.network "private_network", ip: "192.168.50.62"
  #Need to mount it for ansible script
  config.vm.synced_folder "../ansible", "/home/vagrant/ansible"
  #For deploy frontend 
  config.vm.synced_folder "../frontend", "/home/vagrant/frontend"

  #Installs ansible in guest machine and runs provisioning
  config.vm.provision "shell", inline: "yum -y install python-pip gcc python-devel"
  config.vm.provision "shell", inline: "pip install --upgrade pip"
  config.vm.provision "shell", inline: "pip install ansible"
  config.vm.provision "shell", path: "provision.sh"
end
