FROM axeclbr/leiningen

MAINTAINER Oscar Perez  <oscar.perez@gofore.com>

#COPY . /root/hello-lein-docker

#WORKDIR /root/hello-lein-docker

#RUN /usr/local/bin/lein deps

#CMD ["/usr/local/bin/lein", "run"]

EXPOSE 3000