# -*- mode: ruby -*-
# vi: set ft=ruby :

# Docker lapinakyvyys vaati vahintaan Vagrant 1.6
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.box = "ubuntu/trusty64"
   config.ssh.insert_key = false
   config.vm.provision :docker
   config.vm.provision :docker_compose, yml: "/docker-compose.yml", rebuild: true, run: "always"   
end

