VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Configure cached packages to be shared between instances of the same base box.
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  # Define a Docker enabled centos 7.2 host (Vagrant VM) 
  config.vm.define "dockerhost" do |host|
    host.vm.box = "williamyeh/centos7-docker"
    host.vm.provision "docker"
    # disable SSH ??
    # host.vm.provision "shell", inline:
    #  "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
    # forward ports as required (postgresql: 5432, http: 80)
    #Postgresql
    host.vm.network "forwarded_port",
      guest: 5432, host: 5432, auto_correct: true
    #Apache
    host.vm.network "forwarded_port",
      guest: 80, host: 8080, auto_correct: true
    #Node
    host.vm.network "forwarded_port",
      guest: 8080, host: 8081, auto_correct: true
  end
end
