ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# disable parallellism so that the containers come up in order
ENV['VAGRANT_NO_PARALLEL'] = "1"
ENV['FORWARD_DOCKER_PORTS'] = "1"

DOCKER_HOST_NAME = "dockerhost"
DOCKER_HOST_VAGRANTFILE = "docker-host/Vagrantfile"
DOCKER_FOLDER = "../docker/"


Vagrant.configure(2) do |config|
   #Kaytetaan oletus insecure key
   config.ssh.insert_key = false
   #Kehitystyön tietokantapalvelin (postgresql)
   config.vm.define "avop-db" do |avopdb|
     avopdb.vm.provider "docker" do |db|
         # use a vagrant host if required (OSX & Windows)
        db.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
        db.vagrant_machine = "#{DOCKER_HOST_NAME}"
        db.build_dir = "#{DOCKER_FOLDER}/postgresql"
        db.build_args = ["-t=avop-db"]
        db.name = "avop-db"
        db.ports = ["5432:5432"]
        db.remains_running = true 
     end
  end
  
  # Kehitystyön sovelluspalvelin (apache)
   config.vm.define "avop-app" do |avopapp|
     avopapp.vm.provider "docker" do |app|
        app.build_dir = "#{DOCKER_FOLDER}/apache"
        app.build_args = ["-t=avop-db"]
        app.name = "avop-app"
        app.ports = ["8080:80"]
        app.remains_running = true 
     end
  end
end

