ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
ENV['FORWARD_DOCKER_PORTS'] = "1"

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Docker lapinakyvyys vaati vahintaan Vagrant 1.6
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

DOCKER_HOST_NAME = "dockerhost"
DOCKER_FOLDER = "../docker/"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   #Kaytetaan oletus insecure key
   config.ssh.insert_key = false
   
   # Disable synced folders for the Docker container
   # (prevents an NFS error on "vagrant up")
   config.vm.synced_folder ".", "/vagrant", disabled: true

   #Maaritellaan docker host
   config.vm.provider "docker" do |docker|
      docker.image = "xx"
      docker.name = "avop"
      #Postgresql ja web portit
      docker.ports = ["5432:5432", "80:8080"]
  end
end

